# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: debug-statements
        language_version: python3
    -   id: check-merge-conflict
    -   id: check-ast
    -   id: check-json
    -   id: check-shebang-scripts-are-executable
    -   id: check-toml
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: detect-aws-credentials
    -   id: detect-private-key
    -   id: mixed-line-ending
    -   id: pretty-format-json
        args: [--autofix]

-   repo: https://github.com/asottile/reorder_python_imports
    rev: v3.9.0
    hooks:
    -   id: reorder-python-imports
        args: [--application-directories=src, --py310-plus]

-   repo: https://github.com/asottile/pyupgrade
    rev: v3.2.2
    hooks:
    -   id: pyupgrade
        args: [--py310-plus]

-   repo: https://github.com/psf/black
    rev: 22.10.0
    hooks:
    -   id: black
        args: [--safe, --target-version=py310, --line-length=120]
