services:
  app:
    build: .
    container_name: ml_model_fastapi
    command: uvicorn main:app --host 0.0.0.0 --port 5000 --reload
    ports:
      - 5000:5000
    volumes:
      - .:/app
  unittests:
    build: .
    container_name: ml_model_unittests
    command: ./hotload_unittest.sh
    volumes:
      - .:/app
