name: ml_model_fastapi
channels:
  - conda-forge
  - defaults
dependencies:
  - numpy=1.23.4
  - pandas=1.5.1
  - scikit-learn=1.1.3
  - pytest=7.2.0
  - jupyter=1.0.0
  - jupyterlab=3.5.0
  - fastapi=0.86.0
  - uvicorn=0.20.0
  - dvc=2.34.2
  - dvc-s3=2.21.0
  - pre-commit=2.20.0
