name: Python package

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          # Semantic version range syntax or exact version of a Python version
          python-version: '3.10'
          # Optional - x64 or x86 architecture, defaults to x64
          architecture: 'x64'
          cache: 'pip' # caching pip dependencies
      - run: pip install -r requirements.txt
      - name: Run Unit Tests
        run:  PYTHONPATH=${PWD}:${PYTHONPATH} pytest -s -x -vv --failed-first tests
